/**
 * GENERATED by scripts/build-tech-icons.mjs — do not edit by hand.
 * Re-run the script to change the set.
 *
 * Marks from Simple Icons (CC0-1.0). The icons are public domain; the
 * trademarks are not. Each mark remains the property of its owner and is used
 * here only to name a technology.
 *
 * Metadata only. The marks live at public/tech/<id>.svg and are rendered by
 * masking that file, so no path data reaches the bundle.
 */
export type TechMark = {
  id: string
  title: string
  group: string
  /** Official brand colour. */
  hex: string
  /** Whether public/tech/<id>.svg exists yet. */
  asset: boolean
  source: string
  /** Set when the mark is not in Simple Icons and must be supplied by hand. */
  note?: string
}

export const techMarks: TechMark[] = [
  {
    id: "react",
    title: "React",
    group: "Interface",
    hex: "#61DAFB",
    asset: true,
    source: "https://github.com/facebook/create-react-app/blob/282c03f9525fdf8061ffa1ec50dce89296d916bd/test/fixtures/relative-paths/src/logo.svg",
  },
  {
    id: "nextdotjs",
    title: "Next.js",
    group: "Interface",
    hex: "#000000",
    asset: true,
    source: "https://vercel.com/design/brands#next-js",
  },
  {
    id: "typescript",
    title: "TypeScript",
    group: "Interface",
    hex: "#3178C6",
    asset: true,
    source: "https://www.typescriptlang.org/branding",
  },
  {
    id: "tailwindcss",
    title: "Tailwind CSS",
    group: "Interface",
    hex: "#06B6D4",
    asset: true,
    source: "https://tailwindcss.com/brand",
  },
  {
    id: "astro",
    title: "Astro",
    group: "Interface",
    hex: "#BC52EE",
    asset: true,
    source: "https://astro.build/press",
  },
  {
    id: "vite",
    title: "Vite",
    group: "Interface",
    hex: "#9135FF",
    asset: true,
    source: "https://github.com/voidzero-dev/community-design-resources/blob/55902097229cf01cf2a4ceb376f992f5cf306756/brand-assets/vite/vite-icon-color-bracketless.svg",
  },
  {
    id: "flutter",
    title: "Flutter",
    group: "Mobile",
    hex: "#02569B",
    asset: true,
    source: "https://flutter.dev/brand",
  },
  {
    id: "expo",
    title: "Expo",
    group: "Mobile",
    hex: "#1C2024",
    asset: true,
    source: "https://expo.dev/brand/",
  },
  {
    id: "swift",
    title: "Swift",
    group: "Mobile",
    hex: "#F05138",
    asset: true,
    source: "https://developer.apple.com/swift/resources/",
  },
  {
    id: "kotlin",
    title: "Kotlin",
    group: "Mobile",
    hex: "#7F52FF",
    asset: true,
    source: "https://www.jetbrains.com/company/brand/logos/",
  },
  {
    id: "nodedotjs",
    title: "Node.js",
    group: "Backend & data",
    hex: "#5FA04E",
    asset: true,
    source: "https://nodejs.org/en/about/branding",
  },
  {
    id: "postgresql",
    title: "PostgreSQL",
    group: "Backend & data",
    hex: "#4169E1",
    asset: true,
    source: "https://wiki.postgresql.org/wiki/Logo",
  },
  {
    id: "supabase",
    title: "Supabase",
    group: "Backend & data",
    hex: "#3FCF8E",
    asset: true,
    source: "https://github.com/supabase/supabase/blob/4031a7549f5d46da7bc79c01d56be4177dc7c114/packages/common/assets/images/supabase-logo-wordmark--light.svg",
  },
  {
    id: "firebase",
    title: "Firebase",
    group: "Backend & data",
    hex: "#DD2C00",
    asset: true,
    source: "https://firebase.google.com/brand-guidelines",
  },
  {
    id: "prisma",
    title: "Prisma",
    group: "Backend & data",
    hex: "#2D3748",
    asset: true,
    source: "https://github.com/prisma/presskit/tree/4bcb64181f266723439d955d60afa1c55fefa715",
  },
  {
    id: "redis",
    title: "Redis",
    group: "Backend & data",
    hex: "#FF4438",
    asset: true,
    source: "https://redis.io/brand-guidelines",
  },
  {
    id: "docker",
    title: "Docker",
    group: "Infrastructure",
    hex: "#2496ED",
    asset: true,
    source: "https://www.docker.com/company/newsroom/media-resources",
  },
  {
    id: "vercel",
    title: "Vercel",
    group: "Infrastructure",
    hex: "#000000",
    asset: true,
    source: "https://vercel.com/geist/brands",
  },
  {
    id: "cloudflare",
    title: "Cloudflare",
    group: "Infrastructure",
    hex: "#F38020",
    asset: true,
    source: "https://www.cloudflare.com/logo/",
  },
  {
    id: "githubactions",
    title: "GitHub Actions",
    group: "Infrastructure",
    hex: "#2088FF",
    asset: true,
    source: "https://github.com/features/actions",
  },
  {
    id: "sanity",
    title: "Sanity",
    group: "Content & commerce",
    hex: "#0D0E12",
    asset: true,
    source: "https://github.com/sanity-io/logos/blob/e298a1ac2757c83910fe08b496a115bc9aef06bd/src/sanityMonogram.tsx",
  },
  {
    id: "wordpress",
    title: "WordPress",
    group: "Content & commerce",
    hex: "#21759B",
    asset: true,
    source: "https://wordpress.org/about/logos",
  },
  {
    id: "shopify",
    title: "Shopify",
    group: "Content & commerce",
    hex: "#7AB55C",
    asset: true,
    source: "https://www.shopify.com/brand-assets",
  },
  {
    id: "webflow",
    title: "Webflow",
    group: "Content & commerce",
    hex: "#146EF5",
    asset: true,
    source: "https://brand-at.webflow.io/resources#logos",
  },
  {
    id: "resend",
    title: "Resend",
    group: "Product surface",
    hex: "#000000",
    asset: true,
    source: "https://resend.com/brand",
  },
  {
    id: "stripe",
    title: "Stripe",
    group: "Product surface",
    hex: "#635BFF",
    asset: true,
    source: "https://stripe.com/newsroom/information",
  },
  {
    id: "figma",
    title: "Figma",
    group: "Product surface",
    hex: "#F24E1E",
    asset: true,
    source: "https://www.figma.com/using-the-figma-brand/",
  },
  {
    id: "googleanalytics",
    title: "Google Analytics",
    group: "Growth",
    hex: "#E37400",
    asset: true,
    source: "https://marketingplatform.google.com/intl/en_uk/about/analytics/",
  },
  {
    id: "googletagmanager",
    title: "Google Tag Manager",
    group: "Growth",
    hex: "#246FDB",
    asset: true,
    source: "https://tagmanager.google.com/#/home",
  },
  {
    id: "googleads",
    title: "Google Ads",
    group: "Growth",
    hex: "#4285F4",
    asset: true,
    source: "https://ads.google.com/home/",
  },
  {
    id: "meta",
    title: "Meta",
    group: "Growth",
    hex: "#0467DF",
    asset: true,
    source: "https://www.meta.com",
  },
  {
    id: "aws",
    title: "AWS",
    group: "Infrastructure",
    hex: "#FF9900",
    asset: false,
    source: "https://aws.amazon.com/architecture/icons/",
    note: "Removed from Simple Icons at Amazon’s request. Use the official Architecture Icons pack and follow the AWS trademark guidelines.",
  },
]

/** Only the marks whose file exists — what a UI can actually render. */
export const renderableMarks: TechMark[] = techMarks.filter((m) => m.asset)

/** The groups, in the order the script declares them. */
export const techGroups: string[] = [
  "Interface",
  "Mobile",
  "Backend & data",
  "Infrastructure",
  "Content & commerce",
  "Product surface",
  "Growth",
]
